apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-only-binding
  namespace: secure-app
subjects:
- kind: ServiceAccount
  name: secure-sa
  namespace: secure-app
roleRef:
  kind: Role
  name: read-only-role
  apiGroup: rbac.authorization.k8s.io

